"""Jobs router — upload PDF, query job status."""
import json
import os
from pathlib import Path
import uuid
from datetime import datetime, timezone
from typing import Optional

from fastapi import APIRouter, BackgroundTasks, Depends, File, HTTPException, UploadFile
from fastapi.responses import FileResponse, Response
from pydantic import BaseModel, Field
from sqlalchemy import func, or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from database import (
    BOQRow, Job, JobStageEvent, JobStatus, MappingResult, MappingStatus,
    MasterItem, ParsedDocument, UnitRule, Coefficient, RowType, get_db,
)
from parser_adapter.adapter import ParserAdapter, ParserAdapterError
from parser_adapter.normalizer import DocumentNormalizer
from boq.reconstructor import BOQLineItem, BOQReconstructor
from semantic_mapper.mapper import MasterCandidate, SemanticMapper
from pricing_engine.engine import PricingEngine

DEMO_TENANT_ID = os.getenv("DEMO_TENANT_ID", "demo-tenant-001")
MASTER_VERSION = os.getenv("MASTER_DATA_VERSION", "v1")

router = APIRouter()
UAT_BASELINE_FIXTURE = Path(__file__).resolve().parents[2] / "fixtures" / "bang_tien_luong_uat_baseline_95.json"
HISTORICAL_AZURE_FIXTURE = Path(__file__).resolve().parents[2] / "fixtures" / "bang_tien_luong_azure_historical_94.json"


def _document_storage_dir() -> Path:
    """Return the non-public source-document store.

    The directory is configurable for UAT persistent volumes.  It is never
    mounted as static content; documents are only served through the protected
    jobs API.
    """
    configured = os.getenv("DOCUMENT_STORAGE_DIR", "").strip()
    if configured:
        return Path(configured).expanduser().resolve()
    return (Path(__file__).resolve().parents[2] / "runtime" / "documents").resolve()


def _document_path(job_id: str) -> Path:
    # job_id is generated by this service and only used as a filename.  UUID
    # parsing prevents traversal if a caller supplies an arbitrary path value.
    try:
        safe_id = str(uuid.UUID(job_id))
    except ValueError as exc:
        raise HTTPException(404, "Job not found") from exc
    return _document_storage_dir() / f"{safe_id}.pdf"


def _persist_source_document(job_id: str, pdf_bytes: bytes) -> None:
    destination = _document_path(job_id)
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_suffix(".pdf.part")
    try:
        temporary.write_bytes(pdf_bytes)
        temporary.replace(destination)
    finally:
        if temporary.exists():
            temporary.unlink()


class JobStatusResponse(BaseModel):
    job_id: str
    status: str
    filename: str
    error_message: Optional[str] = None
    row_count: Optional[int] = None
    unresolved_count: Optional[int] = None
    source_row_count: Optional[int] = None
    billable_count: Optional[int] = None
    structural_count: Optional[int] = None
    mapping_unresolved_count: Optional[int] = None
    pricing_unavailable_count: Optional[int] = None
    pricing_conflict_count: Optional[int] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    stage_sequence: list[dict] = Field(default_factory=list)


class DocumentPage(BaseModel):
    page: int
    width: float
    height: float
    unit: str


class DocumentMetadata(BaseModel):
    page_count: int
    pages: list[DocumentPage]


def _derive_mapping_status(
    mapping_out,
    price_out,
) -> MappingStatus:
    mapping_status_name = str(
        getattr(mapping_out, "classification", None)
        or getattr(mapping_out, "status", "mapping_unresolved")
    )
    mapped = {
        "mapped_and_priced": MappingStatus.mapped_and_priced,
        "mapped_price_unavailable": MappingStatus.mapped_price_unavailable,
        "mapping_ambiguous": MappingStatus.mapping_ambiguous,
        "mapping_unresolved": MappingStatus.mapping_unresolved,
        "invalid_quantity_or_unit": MappingStatus.invalid_quantity_or_unit,
        "non_billable_heading": MappingStatus.non_billable_heading,
        "non_billable_metadata": MappingStatus.non_billable_metadata,
        "resolved": MappingStatus.mapped_and_priced,
        "unresolved": MappingStatus.mapping_unresolved,
        "error": MappingStatus.mapping_unresolved,
    }
    mapping_status = mapped.get(mapping_status_name, MappingStatus.mapping_unresolved)

    if mapping_status in {MappingStatus.non_billable_heading, MappingStatus.non_billable_metadata}:
        return mapping_status
    if mapping_status in {MappingStatus.mapping_ambiguous, MappingStatus.mapping_unresolved, MappingStatus.invalid_quantity_or_unit}:
        return mapping_status
    if getattr(mapping_out, "master_item_id", None) is None:
        return MappingStatus.mapping_unresolved

    if price_out.status == "priced" and price_out.unit_price_str is not None and price_out.extended_amount_str is not None:
        return MappingStatus.mapped_and_priced
    if price_out.status == "unresolved":
        return MappingStatus.mapped_price_unavailable
    return MappingStatus.mapping_unresolved


async def _transition(db: AsyncSession, job: Job, stage: JobStatus) -> None:
    """Persist the visible state and its audit event atomically."""
    job.status = stage
    db.add(JobStageEvent(job_id=job.id, stage=stage.value))
    await db.commit()


async def _job_status_response(db: AsyncSession, job: Job) -> JobStatusResponse:
    source_count = int(await db.scalar(
        select(func.count()).select_from(BOQRow).where(BOQRow.job_id == job.id)
    ) or 0)
    billable_count = int(await db.scalar(
        select(func.count()).select_from(BOQRow).where(
            BOQRow.job_id == job.id, BOQRow.row_type == RowType.line_item,
        )
    ) or 0)
    issue_statuses = (
        MappingStatus.mapping_ambiguous,
        MappingStatus.mapping_unresolved,
        MappingStatus.invalid_quantity_or_unit,
    )
    mapping_unresolved = int(await db.scalar(
        select(func.count()).select_from(MappingResult).join(BOQRow).where(
            BOQRow.job_id == job.id,
            BOQRow.row_type == RowType.line_item,
            MappingResult.status.in_(issue_statuses),
        )
    ) or 0)
    pricing_unavailable = int(await db.scalar(
        select(func.count()).select_from(MappingResult).join(BOQRow).where(
            BOQRow.job_id == job.id,
            BOQRow.row_type == RowType.line_item,
            MappingResult.status == MappingStatus.mapped_price_unavailable,
        )
    ) or 0)
    pricing_conflicts = int(await db.scalar(
        select(func.count()).select_from(MappingResult).join(BOQRow).where(
            BOQRow.job_id == job.id,
            BOQRow.row_type == RowType.line_item,
            MappingResult.price_review_required.is_(True),
        )
    ) or 0)
    unresolved_total = int(await db.scalar(
        select(func.count()).select_from(MappingResult).join(BOQRow).where(
            BOQRow.job_id == job.id,
            BOQRow.row_type == RowType.line_item,
            or_(
                MappingResult.status.in_((*issue_statuses, MappingStatus.mapped_price_unavailable)),
                MappingResult.price_review_required.is_(True),
            ),
        )
    ) or 0)
    events = (await db.execute(
        select(JobStageEvent).where(JobStageEvent.job_id == job.id).order_by(JobStageEvent.id)
    )).scalars().all()
    return JobStatusResponse(
        job_id=job.id,
        status=job.status,
        filename=job.filename,
        error_message=job.error_message,
        row_count=source_count,
        unresolved_count=unresolved_total,
        source_row_count=source_count,
        billable_count=billable_count,
        structural_count=source_count - billable_count,
        mapping_unresolved_count=mapping_unresolved,
        pricing_unavailable_count=pricing_unavailable,
        pricing_conflict_count=pricing_conflicts,
        created_at=job.created_at,
        updated_at=job.updated_at,
        stage_sequence=[{"stage": event.stage, "occurred_at": event.occurred_at} for event in events],
    )


@router.post("/upload", response_model=JobStatusResponse)
async def upload_pdf(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(...),
    db: AsyncSession = Depends(get_db),
):
    if not file.filename or not file.filename.lower().endswith(".pdf"):
        raise HTTPException(400, "Only PDF files are accepted")

    try:
        pdf_bytes = await file.read()
    except Exception as exc:
        raise HTTPException(400, "Failed to read uploaded file") from exc
    if not pdf_bytes:
        raise HTTPException(400, "Uploaded PDF is empty")

    job_id = str(uuid.uuid4())
    try:
        _persist_source_document(job_id, pdf_bytes)
    except OSError as exc:
        raise HTTPException(500, "Unable to store the source PDF securely") from exc
    job = Job(
        id=job_id,
        tenant_id=DEMO_TENANT_ID,
        filename=file.filename,
        status=JobStatus.uploaded,
    )
    try:
        db.add(job)
        db.add(JobStageEvent(job_id=job_id, stage=JobStatus.uploaded.value))
        await db.commit()
    except Exception:
        _document_path(job_id).unlink(missing_ok=True)
        raise

    background_tasks.add_task(_process_job, job_id, pdf_bytes, file.filename)

    return await _job_status_response(db, job)


@router.post("/uat-validation-import", response_model=JobStatusResponse)
async def import_uat_validation_pdf(
    file: UploadFile = File(...),
    db: AsyncSession = Depends(get_db),
):
    """Create a labelled UAT persistence project without paid provider calls.

    This route is fail-closed outside UAT and must be explicitly enabled. It
    stores the supplied real PDF while loading the already-verified canonical
    source/pricing evidence fixture. It never counts as live Azure/OpenAI proof.
    """
    environment = os.getenv("APP_ENV", os.getenv("ENVIRONMENT", "")).strip().lower()
    enabled = os.getenv("ALLOW_UAT_FIXTURE_IMPORT", "").strip().lower() in {"1", "true", "yes"}
    if environment != "uat" or not enabled:
        raise HTTPException(403, "UAT validation import is disabled")
    if not file.filename or not file.filename.lower().endswith(".pdf"):
        raise HTTPException(400, "Only PDF files are accepted")
    pdf_bytes = await file.read()
    if not pdf_bytes.startswith(b"%PDF-"):
        raise HTTPException(400, "Uploaded file does not have a valid PDF signature")
    try:
        import fitz
        with fitz.open(stream=pdf_bytes, filetype="pdf") as document:
            if document.page_count != 4:
                raise HTTPException(400, "UAT validation requires the four-page sample PDF")
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(400, "Uploaded PDF could not be validated") from exc

    baseline = json.loads(UAT_BASELINE_FIXTURE.read_text(encoding="utf-8"))
    raw_azure = json.loads(HISTORICAL_AZURE_FIXTURE.read_text(encoding="utf-8"))
    rows = baseline.get("rows") or []
    if len(rows) != 95 or sum(bool(row.get("billable")) for row in rows) != 82:
        raise HTTPException(500, "Checked-in UAT source contract is invalid")

    job_id = str(uuid.uuid4())
    _persist_source_document(job_id, pdf_bytes)
    now = datetime.now(timezone.utc)
    job = Job(
        id=job_id,
        tenant_id=f"uat-validation-{job_id}",
        filename=f"[UAT VALIDATION - NOT OFFICIAL] {file.filename}",
        status=JobStatus.needs_review,
    )
    db.add(job)
    for stage in (
        JobStatus.uploaded, JobStatus.parsing, JobStatus.mapping,
        JobStatus.pricing, JobStatus.needs_review,
    ):
        db.add(JobStageEvent(job_id=job_id, stage=stage.value))
    db.add(ParsedDocument(
        job_id=job_id,
        raw_json=json.dumps(raw_azure, ensure_ascii=False),
        page_count=4,
        model_id="prebuilt-layout",
        api_version="2024-11-30",
    ))
    try:
        for source in rows:
            row = BOQRow(
                job_id=job_id,
                row_id=f"uat-source-{int(source['source_index']):03d}",
                row_number=source.get("stt"),
                section_path=source.get("section_path") or "",
                description_vi=source.get("description") or "",
                unit_raw=source.get("unit") or None,
                quantity_raw=source.get("quantity_raw") or None,
                quantity=float(source["quantity"]) if source.get("quantity") not in (None, "") else None,
                page=int(source.get("page") or 1),
                region=json.dumps(source.get("polygon") or []),
                row_type=RowType.line_item if source.get("billable") else RowType.metadata,
                doc_order=int(source["source_index"]),
                source_origin=source.get("source_origin") or "azure_document_intelligence",
                source_provenance=source.get("source_provenance"),
                azure_polygon_available=bool(source.get("azure_polygon_available", True)),
            )
            db.add(row)
            await db.flush()

            master = None
            if source.get("treatment") == "mapped_and_priced":
                master = MasterItem(
                    tenant_id=job.tenant_id,
                    version="source-20260927",
                    item_code=source.get("mapped_work_item") or f"UAT.{source['source_index']}",
                    description_vi=source.get("mapped_description") or source.get("description") or "",
                    unit=source.get("unit") or "",
                    unit_price=float(source["unit_price"]),
                    formula_ref=source.get("formula_ref"),
                    source_sheet=source.get("price_source_reference"),
                    created_by="source-evidence-import",
                    created_at=now,
                    last_updated_by="source-evidence-import",
                    last_updated_at=now,
                    price_source_reference=source.get("price_source_reference"),
                    price_effective_date=None,
                    approval_status="source_verified",
                )
                db.add(master)
                await db.flush()

            is_billable = bool(source.get("billable"))
            status = (
                MappingStatus.mapped_and_priced if master else
                MappingStatus.mapped_price_unavailable if is_billable else
                MappingStatus.non_billable_metadata
            )
            db.add(MappingResult(
                boq_row_id=row.id,
                master_item_id=master.id if master else None,
                status=status,
                confidence=1.0 if master or not is_billable else None,
                evidence="Pre-validated UAT persistence fixture; not a live provider result.",
                unresolved_reason=source.get("reason") if is_billable and not master else None,
                unit_price_str=str(source["unit_price"]) if master else None,
                extended_amount_str=str(source["extension"]) if master else None,
                price_source="source_reconciliation_fixture" if master else None,
                formula_ref=source.get("formula_ref"),
                master_version="source-20260927" if master else None,
                pricing_availability="available" if master else ("not_available" if is_billable else "not_applicable"),
                price_effective_date=None,
                price_source_reference=source.get("price_source_reference") if master else None,
                price_last_updated_by="source-evidence-import" if master else None,
                price_last_updated_at=now if master else None,
                mapping_last_updated_by="source-evidence-import",
                mapping_last_updated_at=now,
                mapped_by="source-evidence-import" if master else None,
            ))
        await db.commit()
    except Exception:
        await db.rollback()
        _document_path(job_id).unlink(missing_ok=True)
        raise

    return await _job_status_response(db, job)


@router.get("/{job_id}/document")
async def get_source_document(job_id: str, db: AsyncSession = Depends(get_db)):
    """Stream the original PDF inline for authenticated review."""
    job = await db.get(Job, job_id)
    if not job:
        raise HTTPException(404, "Job not found")
    document_path = _document_path(job_id)
    if not document_path.is_file():
        raise HTTPException(
            404,
            "Source PDF is unavailable for this job (it may predate document storage)",
        )
    return FileResponse(
        document_path,
        media_type="application/pdf",
        filename=job.filename,
        content_disposition_type="inline",
        headers={"Cache-Control": "private, no-store"},
    )


@router.get("/{job_id}/document/metadata", response_model=DocumentMetadata)
async def get_document_metadata(job_id: str, db: AsyncSession = Depends(get_db)):
    job = await db.get(Job, job_id)
    if not job:
        raise HTTPException(404, "Job not found")
    parsed_document = await db.scalar(
        select(ParsedDocument).where(ParsedDocument.job_id == job_id)
    )
    if not parsed_document:
        raise HTTPException(404, "Parsed document metadata not found")
    try:
        raw = json.loads(parsed_document.raw_json)
    except json.JSONDecodeError as exc:
        raise HTTPException(500, "Stored parser metadata is invalid") from exc
    analyze = raw.get("analyzeResult", raw)
    pages = [
        DocumentPage(
            page=int(page.get("pageNumber", index + 1)),
            width=float(page.get("width", 1)),
            height=float(page.get("height", 1)),
            unit=str(page.get("unit", "inch")),
        )
        for index, page in enumerate(analyze.get("pages", []))
    ]
    return DocumentMetadata(page_count=parsed_document.page_count, pages=pages)


@router.get("/{job_id}/document/pages/{page_number}.png")
async def render_document_page(
    job_id: str,
    page_number: int,
    db: AsyncSession = Depends(get_db),
):
    """Render one protected source page for an overlay-capable review UI."""
    job = await db.get(Job, job_id)
    if not job:
        raise HTTPException(404, "Job not found")
    document_path = _document_path(job_id)
    if not document_path.is_file():
        raise HTTPException(404, "Source PDF is unavailable for this job")
    if page_number < 1:
        raise HTTPException(400, "page_number must be at least 1")
    try:
        import fitz
    except ImportError as exc:  # pragma: no cover - packaging guard
        raise HTTPException(503, "PDF page rendering is not installed") from exc
    try:
        with fitz.open(document_path) as document:
            if page_number > document.page_count:
                raise HTTPException(404, "PDF page not found")
            page = document.load_page(page_number - 1)
            pixmap = page.get_pixmap(matrix=fitz.Matrix(1.65, 1.65), alpha=False)
            png_bytes = pixmap.tobytes("png")
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(422, "Source PDF could not be rendered") from exc
    return Response(
        content=png_bytes,
        media_type="image/png",
        headers={"Cache-Control": "private, no-store"},
    )


@router.get("/{job_id}", response_model=JobStatusResponse)
async def get_job(job_id: str, db: AsyncSession = Depends(get_db)):
    job = await db.get(Job, job_id)
    if not job:
        raise HTTPException(404, "Job not found")
    return await _job_status_response(db, job)


@router.get("/", response_model=list[JobStatusResponse])
async def list_jobs(db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(Job).order_by(Job.created_at.desc()).limit(50))
    jobs = result.scalars().all()
    return [
        JobStatusResponse(
            job_id=j.id,
            status=j.status,
            filename=j.filename,
            error_message=j.error_message,
        )
        for j in jobs
    ]


# ---------------------------------------------------------------------------
# Background pipeline
# ---------------------------------------------------------------------------

async def _process_job(job_id: str, pdf_bytes: bytes, filename: str) -> None:
    from database import AsyncSessionLocal
    async with AsyncSessionLocal() as db:
        job = await db.get(Job, job_id)
        if not job:
            return
        try:
            # --- PARSING ---
            await _transition(db, job, JobStatus.parsing)

            adapter = ParserAdapter()
            raw_result = await adapter.analyze(pdf_bytes)

            normalizer = DocumentNormalizer()
            parsed = normalizer.normalize(raw_result)

            pd_record = ParsedDocument(
                job_id=job_id,
                raw_json=json.dumps(raw_result, ensure_ascii=False),
                page_count=parsed.page_count,
                model_id=parsed.model_id,
                api_version=parsed.api_version,
            )
            db.add(pd_record)
            await db.commit()

            # --- BOQ RECONSTRUCTION ---
            reconstructor = BOQReconstructor()
            boq_items = reconstructor.reconstruct(parsed.boq_rows)

            for item in boq_items:
                row_type_enum = RowType[item.row_type]
                boq_row = BOQRow(
                    job_id=job_id,
                    row_id=item.row_id,
                    row_number=item.row_number,
                    section_path=item.section_path,
                    description_vi=item.description_vi,
                    unit_raw=item.unit_raw,
                    quantity_raw=item.quantity_raw,
                    quantity=item.quantity,
                    page=item.page,
                    region=item.region,
                    row_type=row_type_enum,
                    doc_order=item.doc_order,
                    source_origin=item.source_origin,
                    source_provenance=item.source_provenance,
                    azure_polygon_available=item.azure_polygon_available,
                )
                db.add(boq_row)
            await db.commit()

            # --- MAPPING + PRICING ---
            await _transition(db, job, JobStatus.mapping)

            # Load master data
            masters_q = await db.execute(
                select(MasterItem).where(
                    MasterItem.tenant_id == DEMO_TENANT_ID,
                    MasterItem.version == MASTER_VERSION,
                )
            )
            master_list = masters_q.scalars().all()
            master_dict = {
                m.id: {
                    "id": m.id,
                    "item_code": m.item_code,
                    "description_vi": m.description_vi,
                    "unit": m.unit,
                    "unit_price": m.unit_price,
                    "formula_ref": m.formula_ref,
                    "source_sheet": m.source_sheet,
                    "price_source_reference": m.price_source_reference,
                    "price_effective_date": m.price_effective_date,
                    "price_expiry_date": m.price_expiry_date,
                    "approval_status": m.approval_status,
                    "approved_by": m.approved_by,
                    "zero_price_authorized": m.zero_price_authorized,
                    "tags": json.loads(m.tags_json) if m.tags_json else {},
                }
                for m in master_list
            }

            unit_rules_q = await db.execute(
                select(UnitRule).where(UnitRule.version == MASTER_VERSION)
            )
            unit_rules = [
                {"from_unit": r.from_unit, "to_unit": r.to_unit, "factor": r.factor}
                for r in unit_rules_q.scalars().all()
            ]

            coeffs_q = await db.execute(
                select(Coefficient).where(Coefficient.version == MASTER_VERSION)
            )
            coefficients = [
                {
                    "coeff_code": c.coeff_code,
                    "value": c.value,
                    "applies_to": json.loads(c.applies_to) if c.applies_to else "all",
                }
                for c in coeffs_q.scalars().all()
            ]

            mapper = SemanticMapper()
            engine = PricingEngine()

            boq_rows_q = await db.execute(
                select(BOQRow).where(BOQRow.job_id == job_id).order_by(BOQRow.doc_order)
            )
            db_rows = boq_rows_q.scalars().all()

            mapped_rows = []
            for db_row in db_rows:
                # Build candidates (all master items as candidates for now; real system would use embeddings)
                candidates = [
                    MasterCandidate(
                        id=v["id"],
                        item_code=v["item_code"],
                        description_vi=v["description_vi"],
                        unit=v["unit"],
                        unit_price=v["unit_price"],
                        tags=v["tags"],
                    )
                    for v in master_dict.values()
                ]

                # Reconstruct BOQLineItem
                boq_item = BOQLineItem(
                    row_id=db_row.row_id,
                    row_number=db_row.row_number or "",
                    section_path=db_row.section_path,
                    description_vi=db_row.description_vi,
                    unit_raw=db_row.unit_raw or "",
                    quantity_raw=db_row.quantity_raw or "",
                    quantity=db_row.quantity,
                    page=db_row.page,
                    region=db_row.region or "",
                    row_type=db_row.row_type.value,
                    doc_order=db_row.doc_order,
                    source_origin=db_row.source_origin,
                    source_provenance=db_row.source_provenance or "",
                    azure_polygon_available=db_row.azure_polygon_available,
                )

                mapping_out = await mapper.map_item(boq_item, candidates, MASTER_VERSION)

                mapped_rows.append((db_row, boq_item, mapping_out))

            # Mapping may involve remote semantic calls. Pricing is local and
            # deterministic; do not report "pricing" while mapping is running.
            await _transition(db, job, JobStatus.pricing)

            for db_row, boq_item, mapping_out in mapped_rows:

                price_out = engine.price_row(
                    boq_item, mapping_out, master_dict, unit_rules, coefficients, MASTER_VERSION
                )
                derived_status = _derive_mapping_status(mapping_out, price_out)
                unresolved_reason = mapping_out.unresolved_reason
                if derived_status != MappingStatus.mapped_and_priced and price_out.error_reason:
                    unresolved_reason = price_out.error_reason
                selected_master = next((item for item in master_list if item.id == mapping_out.master_item_id), None)
                now = datetime.now(timezone.utc)

                mr = MappingResult(
                    boq_row_id=db_row.id,
                    master_item_id=mapping_out.master_item_id,
                    status=derived_status,
                    confidence=mapping_out.confidence,
                    tags_json=json.dumps(mapping_out.tags, ensure_ascii=False),
                    evidence=mapping_out.evidence,
                    unresolved_reason=unresolved_reason,
                    unit_price_str=price_out.unit_price_str,
                    extended_amount_str=price_out.extended_amount_str,
                    price_source=price_out.price_source,
                    pricing_availability=price_out.availability_status,
                    price_effective_date=selected_master.price_effective_date if selected_master else None,
                    price_expiry_date=selected_master.price_expiry_date if selected_master else None,
                    price_source_reference=selected_master.price_source_reference if selected_master else None,
                    price_last_updated_by=selected_master.last_updated_by if selected_master else None,
                    price_last_updated_at=selected_master.last_updated_at if selected_master else None,
                    mapping_last_updated_by="system-mapper",
                    mapping_last_updated_at=now,
                    mapped_by="system-mapper" if mapping_out.master_item_id else None,
                    price_review_required=False,
                    formula_ref=price_out.formula_ref,
                    coeff_applied_json=json.dumps(price_out.coeff_applied, ensure_ascii=False),
                    master_version=MASTER_VERSION,
                )
                db.add(mr)

            await db.commit()

            # Reload mapping results to determine final job status
            mrs = await db.execute(
                select(MappingResult).join(BOQRow).where(BOQRow.job_id == job_id)
            )
            mr_list = mrs.scalars().all()
            billable_rows = [
                m for m in mr_list
                if m.boq_row is not None and m.boq_row.row_type == RowType.line_item
            ]
            has_billable_issues = any(
                m.status != MappingStatus.mapped_and_priced
                for m in billable_rows
            )
            await _transition(
                db, job,
                JobStatus.needs_review if has_billable_issues else JobStatus.ready,
            )

        except ParserAdapterError as exc:
            job.error_message = f"Parser error: {exc}"
            await _transition(db, job, JobStatus.failed)
        except Exception as exc:
            job.error_message = f"Pipeline error: {type(exc).__name__}: {exc}"
            await _transition(db, job, JobStatus.failed)
            raise
